services:
  db:
    image: postgres:15
    container_name: postgres_tfg
    restart: always
    environment:
      POSTGRES_DB: tfg_peliculas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - ./datos_sql:/var/lib/postgresql/data
      - ./src/main/resources/db/baseDatosPelis.sql:/docker-entrypoint-initdb.d/baseDatosPelis.sql